### ISSUE TITLE
Could not get an environment up and running

### ISSUE THREAD

**Issue by whotopia** [savannahghi/kenya-emr-releases#2]
Have tried to get test environment for KenyaEMR running on Ubuntu 22.04.3 LTS with both openjdk-8 and openjdk-11 and tomcat9. 
So far I have had no  no luck based the Savanna .xz file and instructions in this repository.

Running into many errors:

1. Note that you must keep openmrs files inside /var/lib/tomcat9, or else systemd will block all other file creation.  So do not e.g. use /var//lib/OpenMRS as your base folder unless you decide to also update the tomcat9 systemd file.  While this is not a problem with this installation per se it was something I ran into having not used tomcat + openmrs a lot.  

2. stuff related to a process that should be listening on port 500 causes all kinds of errors on startup (related to missing afyastat ?)
```
ERROR - ProcessOutboxTask.processFetchedRecord(103) |2023-09-24 15:11:59,239| Illegal character in scheme name at index 0: 127.0.0.1:5000
java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: 127.0.0.1:5000
        at java.net.URI.create(URI.java:852)
        at org.apache.http.client.methods.HttpPost.<init>(HttpPost.java:73)
        at org.openmrs.module.kenyaemrIL.ProcessOutboxTask.processFetchedRecord(ProcessOutboxTask.java:71)
        at org.openmrs.module.kenyaemrIL.ProcessOutboxTask.execute(ProcessOutboxTask.java:43)
        at org.openmrs.scheduler.tasks.TaskThreadedInitializationWrapper.execute(TaskThreadedInitializationWrapper.java:68)
        at org.openmrs.scheduler.timer.TimerSchedulerTask.execute(TimerSchedulerTask.java:94)
        at org.openmrs.api.context.Daemon$3.run(Daemon.java:205)
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0: 127.0.0.1:5000
        at java.net.URI$Parser.fail(URI.java:2847)
        at java.net.URI$Parser.checkChars(URI.java:3020)
        at java.net.URI$Parser.checkChar(URI.java:3030)
        at java.net.URI$Parser.parse(URI.java:3046)
        at java.net.URI.<init>(URI.java:588)
        at java.net.URI.create(URI.java:850)
        ... 6 more
```
```
WARN - HibernateConceptDAO.getConceptByName(1801) |2023-09-24 15:11:59,298| Multiple concepts found for 'mg'
WARN - HibernateConceptDAO.getConceptByName(1801) |2023-09-24 15:12:01,323| Multiple concepts found for 'mg'

```

3.  And then finally on the browser, failed with:

```
Type Exception Report

Message java.lang.UnsupportedClassVersionError: org/eclipse/jdt/internal/compiler/env/INameEnvironment has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.servlet.ServletException: java.lang.UnsupportedClassVersionError: org/eclipse/jdt/internal/compiler/env/INameEnvironment has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:332)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	org.openmrs.web.filter.JspClassLoaderFilter.doFilter(JspClassLoaderFilter.java:47)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:168)
	org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
	org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1228)
	org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1011)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:955)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
```

4. using openjdk-11  the following ... lots of problems creating beans. example:

`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'visitServiceTarget' defined in class path resource [applicationContext-service.xml]: Cannot resolve reference to bean 'visitDAO' while setting bean property 'visitDAO'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'visitDAO' defined in class path resource [applicationContext-service.xml]: Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'sessionFactory': FactoryBean which is currently in creation returned null from getObject`

Can someone provide a clear combination of jvm, and tomcat and instuctions that can be used to get a basic sandbox up and running?

**Comment by kennedykori** [comment]
Hello @whotopia, did you manage to get the EMR running?
